version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r app/requirements.txt -t .
  build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
